# Generated by Django 5.2.12 on 2026-04-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
