# Generated by Django 5.2.15 on 2026-06-13 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_downloads_count_book_is_featured_book_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='banner',
            field=models.FileField(help_text='Majburiy. Kitob detail/reader sahifasidagi keng banner rasmi.', null=True, upload_to='book_banners/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Banner rasmi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.FileField(blank=True, help_text="Katalog kartochkasi uchun vertikal rasm. Bo'lmasa banner fallback sifatida ishlaydi.", null=True, upload_to='books/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Muqova rasmi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(help_text='Majburiy. PDF yuklanmasa kitob saqlanmaydi.', null=True, upload_to='book_pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF kitob'),
        ),
    ]
