# Generated by Django 5.2.15 on 2026-06-13 15:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_banner_alter_book_cover_alter_book_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 yulduz'), (2, '2 yulduz'), (3, '3 yulduz'), (4, '4 yulduz'), (5, '5 yulduz')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Baho')),
                ('comment', models.TextField(max_length=1200, verbose_name='Izoh')),
                ('is_approved', models.BooleanField(default=True, verbose_name="Ko'rinadi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yozilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book', verbose_name='Kitob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Baho va izoh',
                'verbose_name_plural': 'Baholar va izohlar',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['book', 'is_approved'], name='books_bookr_book_id_34a973_idx'), models.Index(fields=['rating'], name='books_bookr_rating_89dc65_idx'), models.Index(fields=['-updated_at'], name='books_bookr_updated_1af3fa_idx')],
                'constraints': [models.UniqueConstraint(fields=('book', 'user'), name='unique_review_per_user_book')],
            },
        ),
    ]
