# Generated by Django 5.2.15 on 2026-06-22 13:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_bookclub_clubmessage_clubreadingplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubreadingplan',
            old_name='book_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='clubreadingplan',
            name='end_page',
        ),
        migrations.RemoveField(
            model_name='clubreadingplan',
            name='start_page',
        ),
        migrations.RemoveField(
            model_name='clubreadingplan',
            name='week_number',
        ),
        migrations.AddField(
            model_name='clubreadingplan',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='club_books/'),
        ),
        migrations.AddField(
            model_name='clubreadingplan',
            name='end_date',
            field=models.DateField(default='2026-01-01'),
        ),
        migrations.AddField(
            model_name='clubreadingplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clubreadingplan',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClubRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookclub')),
            ],
        ),
    ]
