# Generated by Django 5.2.15 on 2026-06-24 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_rename_book_title_clubreadingplan_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookclub',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kitob klubi', 'verbose_name_plural': 'Kitob klublari'},
        ),
        migrations.AlterModelOptions(
            name='clubmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Xabar', 'verbose_name_plural': 'Xabarlar'},
        ),
        migrations.AlterModelOptions(
            name='clubreadingplan',
            options={'ordering': ['-is_active', 'start_date'], 'verbose_name': "O'qish rejasi", 'verbose_name_plural': "O'qish rejalari"},
        ),
        migrations.AlterModelOptions(
            name='clubrule',
            options={'ordering': ['order'], 'verbose_name': 'Qoida', 'verbose_name_plural': 'Qoidalar'},
        ),
        migrations.AddField(
            model_name='bookclub',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_clubs', to=settings.AUTH_USER_MODEL, verbose_name='Adminlar'),
        ),
        migrations.AddField(
            model_name='bookclub',
            name='cover',
            field=models.ImageField(blank=True, help_text="Klub sahifasidagi asosiy rasm. Bo'lmasa default ko'rinadi.", null=True, upload_to='club_covers/', verbose_name='Klub muqovasi'),
        ),
        migrations.AddField(
            model_name='clubreadingplan',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_plans', to='books.book', verbose_name='Kitob'),
        ),
        migrations.AddField(
            model_name='clubreadingplan',
            name='end_page',
            field=models.PositiveIntegerField(default=0, verbose_name='Tugash sahifasi'),
        ),
        migrations.AddField(
            model_name='clubreadingplan',
            name='start_page',
            field=models.PositiveIntegerField(default=1, verbose_name='Boshlanish sahifasi'),
        ),
        migrations.AddField(
            model_name='clubreadingplan',
            name='total_weeks',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='Jami haftalar'),
        ),
        migrations.AddField(
            model_name='clubreadingplan',
            name='week_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Hafta raqami'),
        ),
        migrations.AddField(
            model_name='clubrule',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Ochiq klub'),
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='clubs', to=settings.AUTH_USER_MODEL, verbose_name="A'zolar"),
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Klub nomi'),
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_clubs', to=settings.AUTH_USER_MODEL, verbose_name='Egasi'),
        ),
        migrations.AlterField(
            model_name='clubmessage',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='books.bookclub', verbose_name='Klub'),
        ),
        migrations.AlterField(
            model_name='clubmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vaqt'),
        ),
        migrations.AlterField(
            model_name='clubmessage',
            name='message',
            field=models.TextField(verbose_name='Xabar'),
        ),
        migrations.AlterField(
            model_name='clubmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='clubreadingplan',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_plans', to='books.bookclub', verbose_name='Klub'),
        ),
        migrations.AlterField(
            model_name='clubreadingplan',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='club_books/', verbose_name='Muqova'),
        ),
        migrations.AlterField(
            model_name='clubreadingplan',
            name='end_date',
            field=models.DateField(verbose_name='Tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='clubreadingplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name="Joriy o'qish"),
        ),
        migrations.AlterField(
            model_name='clubreadingplan',
            name='start_date',
            field=models.DateField(verbose_name='Boshlanish sanasi'),
        ),
        migrations.AlterField(
            model_name='clubreadingplan',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name="Kitob nomi (qo'lda)"),
        ),
        migrations.AlterField(
            model_name='clubrule',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='books.bookclub', verbose_name='Klub'),
        ),
        migrations.AlterField(
            model_name='clubrule',
            name='text',
            field=models.TextField(verbose_name='Qoida matni'),
        ),
    ]
