# Generated by Django 5.2.15 on 2026-06-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='VIP foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vip_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='VIP tugash vaqti'),
        ),
    ]
