# Generated by Django 5.2.15 on 2026-06-19 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0007_bookreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Reja nomi')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('tagline', models.CharField(blank=True, max_length=160, verbose_name='Qisqa tavsif')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name="Narx (so'm)")),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='0 = cheksiz', verbose_name='Muddati (kun)')),
                ('features', models.TextField(help_text='Har bir qatorda bitta imkoniyat.', verbose_name='Imkoniyatlar')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Mashhur reja')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'VIP reja',
                'verbose_name_plural': '👑 VIP rejalar',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=64, verbose_name='Sessiya')),
                ('role', models.CharField(choices=[('user', 'Foydalanuvchi'), ('assistant', 'AI yordamchi')], max_length=10, verbose_name='Rol')),
                ('content', models.TextField(verbose_name='Matn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'AI suhbat xabari',
                'verbose_name_plural': '🤖 AI suhbat xabarlari',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VIPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Summa')),
                ('status', models.CharField(choices=[('success', 'Muvaffaqiyatli'), ('failed', 'Xato')], default='success', max_length=10, verbose_name='Holat')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='premium.vipplan', verbose_name='Reja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "VIP to'lov",
                'verbose_name_plural': "💳 VIP to'lovlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Sarlavha')),
                ('message', models.CharField(max_length=300, verbose_name='Xabar')),
                ('icon', models.CharField(choices=[('bell', 'Bell'), ('check', 'Check'), ('crown', 'Crown'), ('heart', 'Heart'), ('target', 'Target'), ('sparkles', 'Sparkles'), ('star', 'Star'), ('book', 'Book'), ('alert', 'Alert')], default='bell', max_length=20, verbose_name='Ikonka')),
                ('link', models.CharField(blank=True, max_length=300, verbose_name='Havola')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': '🔔 Bildirishnomalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='premium_not_user_id_cdfeda_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReadingChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Yil')),
                ('goal', models.PositiveIntegerField(default=12, verbose_name='Maqsad (kitoblar soni)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_challenges', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "O'qish marafoni",
                'verbose_name_plural': "🎯 O'qish marafonlari",
                'ordering': ['-year'],
                'constraints': [models.UniqueConstraint(fields=('user', 'year'), name='unique_challenge_user_year')],
            },
        ),
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('started', 'Boshlandi'), ('continued', 'Davom etildi'), ('completed', 'Tugatildi')], default='continued', max_length=12, verbose_name='Harakat')),
                ('percent_at_event', models.PositiveSmallIntegerField(default=0, verbose_name="O'sha damdagi progress")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='books.book', verbose_name='Kitob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Tarix yozuvi',
                'verbose_name_plural': "📚 O'qish tarixi",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='premium_rea_user_id_7ec382_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveSmallIntegerField(default=0, verbose_name='Progress (%)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tugatilgan')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugatilgan vaqt')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progresses', to='books.book', verbose_name='Kitob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progresses', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "O'qish jarayoni",
                'verbose_name_plural': "📖 O'qish jarayonlari",
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'book'), name='unique_progress_user_book')],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt")),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='books.book', verbose_name='Kitob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Sevimli kitob',
                'verbose_name_plural': '❤ Wishlist',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'book'), name='unique_wishlist_user_book')],
            },
        ),
    ]
